trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 8.3

steps:
# Step 1: Install PHP 8.3 manually
- script: |
    sudo add-apt-repository ppa:ondrej/php -y
    sudo apt-get update
    sudo apt-get install -y php${{ variables.phpVersion }} php${{ variables.phpVersion }}-cli php${{ variables.phpVersion }}-mbstring php${{ variables.phpVersion }}-xml php${{ variables.phpVersion }}-mysql php${{ variables.phpVersion }}-curl php${{ variables.phpVersion }}-opcache php${{ variables.phpVersion }}-xdebug
    sudo update-alternatives --set php /usr/bin/php${{ variables.phpVersion }}
    sudo update-alternatives --set phar /usr/bin/phar${{ variables.phpVersion }}
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg${{ variables.phpVersion }}
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi${{ variables.phpVersion }}
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar${{ variables.phpVersion }}
    php -v
  displayName: 'Install and Use PHP 8.3'

# Step 2: Run Composer Install
- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'

# Add other steps like running tests, build, deploy, etc., if needed.
